# This forces deploy previews to use the state-url
[context.deploy-preview.environment]
	API_BASE_URL = "https://studs-overlord-stage.herokuapp.com"
  
[context.branch-deploy.environment]
	API_BASE_URL = "https://studs-overlord-stage.herokuapp.com"
  
[context.production.environment]
  API_BASE_URL = "https://studs-overlord.herokuapp.com"
