export const GET_EVENTFEEDBACKFORMS_REQUEST =
  'app/EventFeedbackFormPage/GET_EVENTFEEDBACKFORMS_REQUEST'
export const GET_EVENTFEEDBACKFORMS_SUCCESS =
  'app/EventFeedbackFormPage/GET_EVENTFEEDBACKFORMS_SUCCESS'
export const GET_EVENTFEEDBACKFORMS_ERROR =
  'app/EventFeedbackFormPage/GET_EVENTFEEDBACKFORMS_ERROR'
