export const GET_REQUEST = 'app/SalesTool/ContactRequests/GET_REQUEST'
export const GET_SUCCESS = 'app/SalesTool/ContactRequests/GET_SUCCESS'
export const ERROR_ACTION = 'app/SalesTool/ContactRequests/ERROR'
export const UPDATE_REQUEST = 'app/SalesTool/ContactRequests/UPDATE_REQUEST'
export const UPDATE_SUCCESS = 'app/SalesTool/ContactRequests/UPDATE_SUCCESS'
