export const GET_REQUEST = 'app/SalesTool/Contact/GET_REQUEST'
export const GET_SUCCESS = 'app/SalesTool/Contact/GET_SUCCESS'
export const GET_ERROR = 'app/SalesTool/Contact/GET_ERROR'
export const UPDATE_REQUEST = 'app/SalesTool/Contact/UPDATE_REQUEST'
export const UPDATE_SUCCESS = 'app/SalesTool/Contact/UPDATE_SUCCESS'
export const UPDATE_ERROR = 'app/SalesTool/Contact/UPDATE_ERROR'
